"""
FEMA Disaster Assistance - Enhanced Interactive Dashboard
Run with: streamlit run app.py

Folder layout:
    fema_project/
        app.py
        data/
            master_disaster_data.csv
            master_engineered.csv       (generated by train_models.py)
        models/
            train_models.py
            best_model.pkl
            metrics.json
        outputs/
            feature_importance.png
            actual_vs_predicted.png
            model_comparison.png
            vulnerability_vs_assistance.png
            state_year_heatmap.png
            total_vs_housing_by_state.png
            assistance_by_income_bracket.png
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import json
import os
import warnings
warnings.filterwarnings('ignore')

import plotly.express as px
import plotly.graph_objects as go
from PIL import Image

st.set_page_config(
    page_title="FEMA Disaster Assistance",
    page_icon=None,
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
    html, body, [class*="css"] {
        font-family: 'Segoe UI', sans-serif;
    }

    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, #0f2540 0%, #1a3a5c 100%);
    }
    [data-testid="stSidebar"] * {
        color: #e8f0f7 !important;
    }
    [data-testid="stSidebar"] .stSelectbox label,
    [data-testid="stSidebar"] .stMultiSelect label,
    [data-testid="stSidebar"] .stSlider label {
        color: #a8c4de !important;
        font-size: 0.8rem;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }

    .kpi-card {
        background: linear-gradient(135deg, #0f2540 0%, #1e4976 100%);
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 16px;
        padding: 20px 16px;
        text-align: center;
        box-shadow: 0 8px 24px rgba(0,0,0,0.2);
        height: 110px;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }
    .kpi-value {
        font-size: 1.9rem;
        font-weight: 700;
        color: #ffffff;
        line-height: 1.1;
        margin-bottom: 4px;
    }
    .kpi-label {
        font-size: 0.72rem;
        color: #7fb3d3;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        font-weight: 500;
    }

   .section-title {
    font-size: 1.05rem;
    font-weight: 700;
    color: #7fb3d3;   /* lighter blue like the vertical bar */
    border-left: 4px solid #7fb3d3;
    padding-left: 12px;
    margin: 24px 0 14px 0;
    }

    .stTabs [data-baseweb="tab-list"] {
        gap: 4px;
        background: #f0f4f8;
        padding: 6px;
        border-radius: 12px;
    }
    .stTabs [data-baseweb="tab"] {
        background: transparent;
        border-radius: 8px;
        padding: 8px 18px;
        font-weight: 600;
        font-size: 0.85rem;
        color: #4a6080 !important;
        border: none;
    }
    .stTabs [aria-selected="true"] {
        background: #ffffff !important;
        color: #0f2540 !important;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .stTabs [data-baseweb="tab"] p {
        color: inherit !important;
    }

    .img-card {
        background: #ffffff;
        border: 1px solid #e2e8f0;
        border-radius: 12px;
        padding: 16px;
        box-shadow: 0 2px 12px rgba(0,0,0,0.06);
        margin-bottom: 16px;
    }
    .img-caption {
        background: #f8fafc;
        border-left: 3px solid #1e88e5;
        padding: 10px 14px;
        border-radius: 0 8px 8px 0;
        font-size: 0.85rem;
        color: #4a6080;
        margin-top: 12px;
        line-height: 1.5;
    }

    .insight-box {
        background: linear-gradient(135deg, #e8f4fd 0%, #f0f8ff 100%);
        border: 1px solid #b3d9f7;
        border-radius: 12px;
        padding: 16px 20px;
        font-size: 0.88rem;
        color: #1a3a5c;
        line-height: 1.6;
        margin: 12px 0;
    }

    .pred-main {
        background: linear-gradient(135deg, #1565c0 0%, #1e88e5 100%);
        border-radius: 16px;
        padding: 24px;
        text-align: center;
        color: white;
        box-shadow: 0 8px 24px rgba(21,101,192,0.3);
    }
    .pred-main .amount { font-size: 2.2rem; font-weight: 800; }
    .pred-main .label  { font-size: 0.78rem; opacity: 0.85; text-transform: uppercase; letter-spacing: 0.1em; margin-top: 4px; }
    .pred-range {
        background: #f0f4f8;
        border-radius: 12px;
        padding: 14px;
        text-align: center;
        border: 1px solid #dde4ed;
        margin-bottom: 10px;
    }
    .pred-range .amount { font-size: 1.3rem; font-weight: 700; color: #1a3a5c; }
    .pred-range .label  { font-size: 0.72rem; color: #6b8caa; text-transform: uppercase; letter-spacing: 0.08em; margin-top: 4px; }

    .custom-divider {
        border: none;
        height: 1px;
        background: linear-gradient(90deg, transparent, #cbd5e0, transparent);
        margin: 24px 0;
    }

    .gauge-label {
        text-align: center;
        font-size: 0.78rem;
        color: #6b8caa;
        margin-top: 4px;
    }

    .page-header {
        background: linear-gradient(135deg, #0f2540 0%, #1a3a5c 50%, #1e5080 100%);
        border-radius: 16px;
        padding: 28px 32px;
        margin-bottom: 24px;
        color: white;
    }
    .page-header h1 {
        font-size: 1.75rem;
        font-weight: 800;
        margin: 0 0 4px 0;
        color: white;
    }
    .page-header p {
        font-size: 0.88rem;
        opacity: 0.7;
        margin: 0;
        color: white;
    }

    .block-container { padding-top: 1.5rem; }
</style>
""", unsafe_allow_html=True)


BASE       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR   = os.path.join(BASE, "data")
MODEL_DIR  = os.path.join(BASE, "models")
OUTPUT_DIR = os.path.join(BASE, "outputs")


@st.cache_data
def load_data():
    eng_path = os.path.join(DATA_DIR, "master_engineered.csv")
    raw_path = os.path.join(DATA_DIR, "master_disaster_data.csv")

    if os.path.exists(eng_path):
        df = pd.read_csv(eng_path)
    else:
        df = pd.read_csv(raw_path)
        df = df[df['median_income'] > 0].copy()
        df['assistance_per_capita']    = df['total_assistance_amount'] / df['total_population']
        df['assistance_per_applicant'] = df['total_assistance_amount'] / df['total_applicants'].replace(0, np.nan)
        df['applicants_per_capita']    = df['total_applicants'] / df['total_population']
        df['housing_share']            = (
            df['housing_assistance_amount'] / df['total_assistance_amount'].replace(0, np.nan)
        ).fillna(0).clip(0, 1)
        df['z_poverty'] = (df['poverty_rate'] - df['poverty_rate'].mean()) / df['poverty_rate'].std()
        df['z_income']  = -(df['median_income'] - df['median_income'].mean()) / df['median_income'].std()
        df['vulnerability_index']    = (df['z_poverty'] + df['z_income']) / 2
        df['log_total_assistance']   = np.log1p(df['total_assistance_amount'])
        df['log_assistance_per_cap'] = np.log1p(df['assistance_per_capita'])
        df['log_applicants']         = np.log1p(df['total_applicants'])
        df['log_population']         = np.log1p(df['total_population'])
        df['log_income']             = np.log1p(df['median_income'])
        state_mean = df.groupby('state_clean')['log_total_assistance'].mean().rename('state_mean_log_assistance')
        df = df.join(state_mean, on='state_clean')
        df['income_bracket'] = pd.cut(df['median_income'],
            bins=[0, 35000, 50000, 65000, 85000, 200000],
            labels=['Very Low', 'Low', 'Middle', 'Upper-Middle', 'High'])
        df['poverty_tier'] = pd.cut(df['poverty_rate'],
            bins=[0, 10, 20, 30, 100],
            labels=['Low (<10%)', 'Moderate (10-20%)', 'High (20-30%)', 'Extreme (30%+)'])
    return df


@st.cache_resource
def load_model():
    model_path   = os.path.join(MODEL_DIR, "best_model.pkl")
    metrics_path = os.path.join(MODEL_DIR, "metrics.json")
    model_data, metrics = None, None
    if os.path.exists(model_path):
        with open(model_path, "rb") as f:
            model_data = pickle.load(f)
    if os.path.exists(metrics_path):
        with open(metrics_path, "r") as f:
            metrics = json.load(f)
    return model_data, metrics


def load_output_image(filename):
    path = os.path.join(OUTPUT_DIR, filename)
    if os.path.exists(path):
        return Image.open(path)
    return None


df = load_data()
model_data, metrics = load_model()


# Sidebar
with st.sidebar:
    st.markdown("## FEMA Dashboard")
    st.markdown("<p style='font-size:0.78rem; opacity:0.6; margin-top:-8px;'>Disaster Assistance Analysis 2019-2022</p>", unsafe_allow_html=True)
    st.markdown("<hr style='border-color:rgba(255,255,255,0.1); margin:12px 0;'>", unsafe_allow_html=True)

    all_years  = sorted(df['Year'].unique())
    all_states = ['All States'] + sorted(df['state_clean'].unique())

    sel_years = st.multiselect("Filter by Year", all_years, default=all_years)
    sel_state = st.selectbox("Filter by State", all_states)

    if sel_state != 'All States':
        county_options = ['All Counties'] + sorted(df[df['state_clean'] == sel_state]['county_clean'].unique())
        sel_county = st.selectbox("Filter by County", county_options)
    else:
        sel_county = 'All Counties'

    st.markdown("<hr style='border-color:rgba(255,255,255,0.1); margin:12px 0;'>", unsafe_allow_html=True)
    min_pop = int(df['total_population'].min())
    max_pop = int(df['total_population'].max())
    pop_range = st.slider("Population Range", min_pop, min(max_pop, 2_000_000),
                          (min_pop, min(max_pop, 2_000_000)), step=10_000, format="%,d")

    st.markdown("<hr style='border-color:rgba(255,255,255,0.1); margin:12px 0;'>", unsafe_allow_html=True)
    st.markdown("<p style='font-size:0.73rem; opacity:0.5; line-height:1.6;'>Data: FEMA OpenFEMA + US Census ACS<br>Model: Random Forest (R2 = 0.895)</p>", unsafe_allow_html=True)


# Apply filters
fdf = df[df['Year'].isin(sel_years)].copy()
if sel_state != 'All States':
    fdf = fdf[fdf['state_clean'] == sel_state]
if sel_county != 'All Counties':
    fdf = fdf[fdf['county_clean'] == sel_county]
fdf = fdf[(fdf['total_population'] >= pop_range[0]) & (fdf['total_population'] <= pop_range[1])]


# Page header
filter_desc = (
    f"{sel_state if sel_state != 'All States' else 'All States'} | "
    f"Years: {', '.join(map(str, sel_years))} | "
    f"{len(fdf):,} county-year records"
)
st.markdown(f"""
<div class="page-header">
    <h1>FEMA Disaster Assistance Dashboard</h1>
    <p>{filter_desc}</p>
</div>
""", unsafe_allow_html=True)


# KPI cards
def kpi(col, value, label):
    col.markdown(f"""
    <div class="kpi-card">
        <div class="kpi-value">{value}</div>
        <div class="kpi-label">{label}</div>
    </div>""", unsafe_allow_html=True)

k1, k2, k3, k4, k5 = st.columns(5)
kpi(k1, f"${fdf['total_assistance_amount'].sum()/1e9:.2f}B", "Total Assistance")
kpi(k2, f"{fdf['total_applicants'].sum()/1e6:.2f}M",         "Total Applicants")
kpi(k3, f"{fdf['county_clean'].nunique():,}",                 "Counties Affected")
kpi(k4, f"${fdf['assistance_per_capita'].mean():.0f}",        "Avg Aid per Capita")
kpi(k5, f"{fdf['poverty_rate'].mean():.1f}%",                 "Avg Poverty Rate")

st.markdown("<br>", unsafe_allow_html=True)

# Key Insights Panel
st.markdown('<div class="section-title">Key Insights</div>', unsafe_allow_html=True)

st.markdown("""
<div class="insight-box">

<b>Major Findings from the Analysis</b><br><br>

• <b>Disaster demand drives FEMA spending.</b> Total applicants strongly correlate with assistance (r ≈ 0.87).  
• <b>Louisiana counties receive the highest per-capita aid</b> due to repeated hurricane disasters.  
• <b>Poverty rate alone is a weak predictor</b> of assistance distribution. FEMA funding primarily follows disaster demand rather than socioeconomic status.  
• <b>Random Forest achieved the best predictive performance</b> with <b>R² = 0.895</b>, explaining nearly 90% of assistance variability.  
• <b>Extreme disaster years like 2020</b> significantly increase nationwide assistance due to large-scale declarations.

</div>
""", unsafe_allow_html=True)

# Tabs
tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
    "Geographic Analysis",
    "Trends Over Time",
    "Socioeconomic Relationships",
    "Predictive Model",
    "Data Explorer",
    "Future Scenarios",
])


# Tab 1: Geographic Analysis
with tab1:
    st.markdown('<div class="section-title">Assistance Distribution by State</div>', unsafe_allow_html=True)

    metric_options = {
        "Total Assistance ($)":      "total_assistance_amount",
        "Assistance per Capita ($)": "assistance_per_capita",
        "Total Applicants":          "total_applicants",
        "Poverty Rate (%)":          "poverty_rate",
        "Vulnerability Index":       "vulnerability_index",
    }
    selected_label = st.radio("Map Metric", list(metric_options.keys()), horizontal=True)
    map_metric = metric_options[selected_label]

    state_summary = fdf.groupby('state_clean').agg(
        total_assistance_amount=('total_assistance_amount', 'sum'),
        assistance_per_capita=('assistance_per_capita', 'mean'),
        total_applicants=('total_applicants', 'sum'),
        poverty_rate=('poverty_rate', 'mean'),
        vulnerability_index=('vulnerability_index', 'mean'),
    ).reset_index()

    fig_map = px.choropleth(
        state_summary,
        locations='state_clean', locationmode='USA-states',
        color=map_metric, scope='usa',
        color_continuous_scale='YlOrRd',
        labels={map_metric: selected_label},
        title=f"{selected_label} by State",
        hover_data={
            'state_clean': True,
            'total_assistance_amount': ':$,.0f',
            'total_applicants': ':,',
            'poverty_rate': ':.1f',
        }
    )
    fig_map.add_trace(go.Scattergeo(
        locations=state_summary['state_clean'],
        locationmode='USA-states',
        text=state_summary['state_clean'],
        mode='text',
        textfont=dict(size=9, color='black'),
        showlegend=False, hoverinfo='skip',
    ))
    fig_map.update_layout(
        height=460, margin=dict(l=0, r=0, t=40, b=0),
        paper_bgcolor='rgba(0,0,0,0)',
        geo=dict(bgcolor='rgba(0,0,0,0)'),
    )
    st.plotly_chart(fig_map, use_container_width=True)

    c1, c2 = st.columns(2)

    with c1:
        st.markdown('<div class="section-title">Top 15 States by Total Assistance</div>', unsafe_allow_html=True)
        top15 = state_summary.nlargest(15, 'total_assistance_amount').sort_values('total_assistance_amount')
        fig_bar = go.Figure(go.Bar(
            y=top15['state_clean'],
            x=top15['total_assistance_amount'] / 1e6,
            orientation='h',
            marker=dict(color=top15['total_assistance_amount'], colorscale='Blues', showscale=False),
            text=[f"${v:.0f}M" for v in top15['total_assistance_amount'] / 1e6],
            textposition='outside',
        ))
        fig_bar.update_layout(
            height=420, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
            xaxis_title="Total Assistance ($ Millions)",
            margin=dict(l=0, r=60, t=10, b=0),
        )
        st.plotly_chart(fig_bar, use_container_width=True)

    with c2:
        st.markdown('<div class="section-title">Top 10 Counties by Aid per Capita</div>', unsafe_allow_html=True)
        top_counties = fdf.nlargest(10, 'assistance_per_capita')[[
            'Year', 'state_clean', 'county_clean', 'poverty_rate',
            'total_assistance_amount', 'assistance_per_capita'
        ]].copy()
        fig_county = go.Figure(go.Bar(
            y=[f"{r['county_clean']}, {r['state_clean']}" for _, r in top_counties.iterrows()],
            x=top_counties['assistance_per_capita'],
            orientation='h',
            marker=dict(color='#e53935', opacity=0.85),
            text=[f"${v:,.0f}" for v in top_counties['assistance_per_capita']],
            textposition='outside',
        ))
        fig_county.update_layout(
            height=420, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
            xaxis_title="Assistance per Capita ($)",
            margin=dict(l=0, r=80, t=10, b=0),
        )
        st.plotly_chart(fig_county, use_container_width=True)

    img_heatmap = load_output_image("state_year_heatmap.png")
    if img_heatmap:
        st.markdown('<div class="section-title">State-by-Year Assistance Heatmap</div>', unsafe_allow_html=True)
        st.markdown('<div class="img-card">', unsafe_allow_html=True)
        st.image(img_heatmap, use_container_width=True)
        st.markdown('<div class="img-caption">Darker red means more total assistance. The 2020 column is uniformly intense due to nationwide COVID-19 disaster declarations. Louisiana and Kentucky stand out in 2021-2022 from hurricanes and flooding.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)


# Tab 2: Trends Over Time
with tab2:
    yearly = fdf.groupby('Year').agg(
        total_assistance=('total_assistance_amount', 'sum'),
        housing_assistance=('housing_assistance_amount', 'sum'),
        total_applicants=('total_applicants', 'sum'),
        n_counties=('county_clean', 'nunique'),
    ).reset_index()

    st.markdown('<div class="section-title">Total vs. Housing Assistance by Year</div>', unsafe_allow_html=True)
    fig_trend = go.Figure()
    fig_trend.add_trace(go.Scatter(
        x=yearly['Year'], y=yearly['total_assistance'] / 1e6,
        mode='lines+markers+text', name='Total Assistance',
        line=dict(color='#1e88e5', width=3), marker=dict(size=10),
        text=[f"${v:.0f}M" for v in yearly['total_assistance'] / 1e6],
        textposition='top center',
    ))
    fig_trend.add_trace(go.Scatter(
        x=yearly['Year'], y=yearly['housing_assistance'] / 1e6,
        mode='lines+markers+text', name='Housing Assistance',
        line=dict(color='#e53935', width=3, dash='dash'), marker=dict(size=10),
        text=[f"${v:.0f}M" for v in yearly['housing_assistance'] / 1e6],
        textposition='bottom center',
    ))
    fig_trend.update_layout(
        height=360, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
        yaxis_title="Assistance ($ Millions)", hovermode='x unified',
        legend=dict(orientation='h', y=1.1),
        xaxis=dict(tickmode='array', tickvals=yearly['Year'].tolist()),
    )
    st.plotly_chart(fig_trend, use_container_width=True)

    c1, c2 = st.columns(2)
    with c1:
        st.markdown('<div class="section-title">Total Applicants by Year</div>', unsafe_allow_html=True)
        fig_apps = go.Figure(go.Bar(
            x=yearly['Year'].astype(str), y=yearly['total_applicants'] / 1e3,
            marker_color=['#1e88e5', '#e53935', '#43a047', '#fb8c00'][:len(yearly)],
            text=[f"{v:.0f}K" for v in yearly['total_applicants'] / 1e3],
            textposition='outside',
        ))
        fig_apps.update_layout(
            height=340, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
            yaxis_title="Applicants (Thousands)", margin=dict(t=10),
        )
        st.plotly_chart(fig_apps, use_container_width=True)

    with c2:
        st.markdown('<div class="section-title">Counties Receiving Aid by Year</div>', unsafe_allow_html=True)
        fig_counties = go.Figure(go.Scatter(
            x=yearly['Year'], y=yearly['n_counties'],
            mode='lines+markers', fill='tozeroy',
            fillcolor='rgba(30,136,229,0.1)',
            line=dict(color='#1e88e5', width=2.5), marker=dict(size=9),
        ))
        fig_counties.update_layout(
            height=340, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
            yaxis_title="Number of Counties",
            xaxis=dict(tickmode='array', tickvals=yearly['Year'].tolist()),
            margin=dict(t=10),
        )
        st.plotly_chart(fig_counties, use_container_width=True)

    st.markdown('<div class="section-title">County Assistance Distribution by Year (Log Scale)</div>', unsafe_allow_html=True)
    fig_box = px.box(
        fdf[fdf['total_assistance_amount'] > 0],
        x='Year', y='total_assistance_amount', color='Year', log_y=True,
        color_discrete_sequence=['#1e88e5', '#e53935', '#43a047', '#fb8c00'],
        labels={'total_assistance_amount': 'Total Assistance ($, log scale)'},
    )
    fig_box.update_layout(
        height=360, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
        showlegend=False, margin=dict(t=10),
    )
    st.plotly_chart(fig_box, use_container_width=True)

    img_housing = load_output_image("total_vs_housing_by_state.png")
    if img_housing:
        st.markdown('<div class="section-title">Total vs. Housing Assistance - Top 15 States</div>', unsafe_allow_html=True)
        st.markdown('<div class="img-card">', unsafe_allow_html=True)
        st.image(img_housing, use_container_width=True)
        st.markdown('<div class="img-caption">Louisiana receives far more housing assistance than any other state, reflecting the level of physical property damage from its multiple hurricanes. For states like Florida and California, non-housing assistance (financial aid) makes up a larger share.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)


# Tab 3: Socioeconomic Relationships
with tab3:
    st.markdown('<div class="section-title">Explore Variable Relationships</div>', unsafe_allow_html=True)

    c1, c2 = st.columns(2)
    with c1:
        x_axis = st.selectbox("X-axis Variable", [
            'poverty_rate', 'median_income', 'total_population',
            'vulnerability_index', 'poverty_count',
        ], format_func=lambda x: {
            'poverty_rate':        'Poverty Rate (%)',
            'median_income':       'Median Income ($)',
            'total_population':    'Total Population',
            'vulnerability_index': 'Vulnerability Index',
            'poverty_count':       'Poverty Count',
        }[x])
    with c2:
        y_axis = st.selectbox("Y-axis Variable", [
            'assistance_per_capita', 'total_assistance_amount',
            'applicants_per_capita', 'housing_share',
        ], format_func=lambda y: {
            'assistance_per_capita':   'Assistance per Capita ($)',
            'total_assistance_amount': 'Total Assistance ($)',
            'applicants_per_capita':   'Applicants per Capita',
            'housing_share':           'Housing Share',
        }[y])

    scatter_df = fdf[(fdf[x_axis].notna()) & (fdf[y_axis].notna()) & (fdf[y_axis] > 0)]
    fig_scatter = px.scatter(
        scatter_df, x=x_axis, y=y_axis,
        color='state_clean',
        hover_data=['county_clean', 'Year', 'poverty_rate', 'median_income'],
        opacity=0.6, log_y=True, trendline='ols',
        labels={
            x_axis: x_axis.replace('_', ' ').title(),
            y_axis: y_axis.replace('_', ' ').title(),
        },
        color_discrete_sequence=px.colors.qualitative.Alphabet,
    )
    fig_scatter.update_layout(
        height=440, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
        showlegend=False, margin=dict(t=10),
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

    c1, c2 = st.columns(2)

    with c1:
        st.markdown('<div class="section-title">Correlation with Total Assistance</div>', unsafe_allow_html=True)
        corr_vars = [
            'total_population', 'median_income', 'poverty_rate', 'poverty_count',
            'vulnerability_index', 'total_applicants',
            'housing_assistance_amount', 'assistance_per_capita', 'applicants_per_capita'
        ]
        corr_vars = [c for c in corr_vars if c in fdf.columns]
        corr_vals = fdf[corr_vars + ['total_assistance_amount']].corr()['total_assistance_amount'].drop('total_assistance_amount').sort_values()
        fig_corr = go.Figure(go.Bar(
            y=corr_vals.index,
            x=corr_vals.values,
            orientation='h',
            marker_color=['#e53935' if v > 0 else '#1e88e5' for v in corr_vals.values],
            text=[f"{v:.2f}" for v in corr_vals.values],
            textposition='outside',
        ))
        fig_corr.update_layout(
            height=360, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
            xaxis_title="Pearson Correlation",
            xaxis=dict(range=[-0.1, 1.1]),
            margin=dict(l=0, r=50, t=10, b=0),
        )
        st.plotly_chart(fig_corr, use_container_width=True)

    with c2:
        st.markdown('<div class="section-title">Assistance by Poverty Tier</div>', unsafe_allow_html=True)
        if 'poverty_tier' in fdf.columns:
            ptier = (
                fdf[fdf['poverty_tier'].notna()]
                .groupby('poverty_tier', observed=False)
                .agg(avg=('assistance_per_capita', 'mean'), med=('assistance_per_capita', 'median'))
                .reset_index()
            )
            fig_ptier = go.Figure()
            fig_ptier.add_trace(go.Bar(
                x=ptier['poverty_tier'].astype(str), y=ptier['avg'],
                name='Mean', marker_color='#e53935', opacity=0.85,
            ))
            fig_ptier.add_trace(go.Bar(
                x=ptier['poverty_tier'].astype(str), y=ptier['med'],
                name='Median', marker_color='#1e88e5', opacity=0.85,
            ))
            fig_ptier.update_layout(
                height=360, plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)',
                barmode='group', yaxis_title="Assistance per Capita ($)",
                legend=dict(orientation='h', y=1.05), margin=dict(t=10),
            )
            st.plotly_chart(fig_ptier, use_container_width=True)

    img_vuln = load_output_image("vulnerability_vs_assistance.png")
    if img_vuln:
        st.markdown('<div class="section-title">Socioeconomic Vulnerability vs. Per-Capita Assistance</div>', unsafe_allow_html=True)
        st.markdown('<div class="img-card">', unsafe_allow_html=True)
        st.image(img_vuln, use_container_width=True)
        st.markdown('<div class="img-caption">The vulnerability index combines poverty rate and median income into one score. The trend line shows a slight positive relationship but the wide scatter shows disaster exposure and applicant volume explain far more variance than socioeconomic status alone.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

    img_income = load_output_image("assistance_by_income_bracket.png")
    if img_income:
        st.markdown('<div class="section-title">Per-Capita Assistance by County Income Bracket</div>', unsafe_allow_html=True)
        st.markdown('<div class="img-card">', unsafe_allow_html=True)
        st.image(img_income, use_container_width=True)
        st.markdown('<div class="img-caption">Counties across all income brackets receive similar median per-capita assistance. FEMA disbursements respond to disaster severity and demand, not pre-existing wealth levels of the affected area.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)


# Tab 4: Model Results
with tab4:
    st.markdown('<div class="section-title">Model Performance Summary</div>', unsafe_allow_html=True)

    if metrics:
        best_r2 = max(m['test_r2'] for m in metrics.values())
        m1, m2, m3 = st.columns(3)
        for col, (mname, mvals) in zip([m1, m2, m3], metrics.items()):
            is_best = mvals['test_r2'] == best_r2
            col.markdown(f"""
            <div style="background:{'linear-gradient(135deg,#0f2540,#1e4976)' if is_best else '#f8fafc'};
                        border:{'2px solid #1e88e5' if is_best else '1px solid #e2e8f0'};
                        border-radius:12px; padding:20px; text-align:center;
                        box-shadow:{'0 8px 24px rgba(30,136,229,0.2)' if is_best else 'none'};">
                <div style="font-size:0.73rem; text-transform:uppercase; letter-spacing:0.1em;
                            color:{'#7fb3d3' if is_best else '#6b8caa'}; margin-bottom:6px;">
                    {'Best Model | ' if is_best else ''}{mname}
                </div>
                <div style="font-size:2rem; font-weight:800; color:{'#ffffff' if is_best else '#0f2540'};">
                    {mvals['test_r2']:.3f}
                </div>
                <div style="font-size:0.78rem; color:{'#a8c4de' if is_best else '#8096a8'}; margin-top:4px;">
                    R2 Score
                </div>
                <div style="margin-top:10px; font-size:0.76rem; color:{'#7fb3d3' if is_best else '#8096a8'};">
                    CV R2: {mvals['cv_r2_mean']:.3f} | MAE: {mvals['test_mae']:.3f}
                </div>
            </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    img_compare = load_output_image("model_comparison.png")
    if img_compare:
        st.markdown('<div class="section-title">Model Comparison - R2 and MAE</div>', unsafe_allow_html=True)
        st.markdown('<div class="img-card">', unsafe_allow_html=True)
        st.image(img_compare, use_container_width=True)
        st.markdown('<div class="img-caption">Random Forest scores highest on R2 (0.896), explaining about 90% of the variance in assistance amounts. Ridge Regression has the highest error because it assumes linearity which does not hold well here. Gradient Boosting is competitive but slightly behind.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

    img_avp = load_output_image("actual_vs_predicted.png")
    if img_avp:
        st.markdown('<div class="section-title">Actual vs. Predicted Assistance - All Models</div>', unsafe_allow_html=True)
        st.markdown('<div class="img-card">', unsafe_allow_html=True)
        st.image(img_avp, use_container_width=True)
        st.markdown('<div class="img-caption">Points close to the red dashed line mean the model predicted correctly. Random Forest has the tightest cluster. All models struggle slightly with extreme outlier counties driven by rare catastrophic events.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

    img_fi = load_output_image("feature_importance.png")
    if img_fi:
        st.markdown('<div class="section-title">Feature Importance - What Drives the Prediction</div>', unsafe_allow_html=True)
        st.markdown('<div class="img-card">', unsafe_allow_html=True)
        st.image(img_fi, use_container_width=True)
        st.markdown('<div class="img-caption">Total applicants (log_applicants) overwhelmingly dominates with an importance score above 0.85. This confirms that demand volume is the primary driver of FEMA disbursements. Poverty rate and vulnerability index have very low importance - socioeconomic status alone does not predict assistance amounts well.</div>', unsafe_allow_html=True)
        st.markdown('</div>', unsafe_allow_html=True)

    st.markdown("""<div class="insight-box">
    <b>Why log transformation?</b> Assistance amounts span several orders of magnitude - from a few hundred dollars
    to hundreds of millions. The model predicts log(total_assistance_amount) and results are back-transformed
    using expm1(). Without this, extreme outliers would dominate and the model would perform poorly on typical counties.
    </div>""", unsafe_allow_html=True)


# Tab 5: Predict Assistance
with tab5:
    st.markdown('<div class="section-title">Estimate FEMA Assistance for a County</div>', unsafe_allow_html=True)
    st.write("Enter county characteristics and the Random Forest model will estimate total assistance needed.")

    st.markdown("<br>", unsafe_allow_html=True)
    p1, p2, p3 = st.columns(3)

    with p1:
        st.markdown("**Population and Income**")
        pred_pop     = st.number_input("Total Population", 500, 10_000_000, 50_000, 1_000, format="%d")
        pred_income  = st.number_input("Median Household Income ($)", 10_000, 200_000, 52_000, 1_000, format="%d")
        pred_poverty = st.slider("Poverty Rate (%)", 0.0, 60.0, 15.0, 0.5)

    with p2:
        st.markdown("**Disaster Characteristics**")
        pred_applicants = st.number_input("Estimated Applicants", 1, 200_000, 200, 10, format="%d")
        pred_year       = st.selectbox("Year", [2019, 2020, 2021, 2022, 2023], index=1)
        pred_state      = st.selectbox("State", sorted(df['state_clean'].unique()))

    with p3:
        st.markdown("**Assistance Type**")
        pred_housing_share = st.slider("Expected Housing Assistance Share", 0.0, 1.0, 0.4, 0.05)
        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("<br>", unsafe_allow_html=True)
        predict_btn = st.button("Run Prediction", type="primary", use_container_width=True)

    st.markdown("<hr class='custom-divider'>", unsafe_allow_html=True)

    if predict_btn and model_data:
        model      = model_data['model']
        feat_names = model_data['features']

        poverty_count  = pred_poverty / 100 * pred_pop
        state_mean_val = df[df['state_clean'] == pred_state]['log_total_assistance'].mean()
        z_pov = (pred_poverty - df['poverty_rate'].mean()) / df['poverty_rate'].std()
        z_inc = -(pred_income - df['median_income'].mean()) / df['median_income'].std()
        vuln  = (z_pov + z_inc) / 2

        feat_vals = {
            'log_population':            np.log1p(pred_pop),
            'log_income':                np.log1p(pred_income),
            'poverty_rate':              pred_poverty,
            'poverty_count':             poverty_count,
            'vulnerability_index':       vuln,
            'applicants_per_capita':     pred_applicants / pred_pop,
            'log_applicants':            np.log1p(pred_applicants),
            'housing_share':             pred_housing_share,
            'Year':                      pred_year,
            'state_mean_log_assistance': state_mean_val,
        }
        X_pred      = pd.DataFrame([[feat_vals[f] for f in feat_names]], columns=feat_names)
        log_pred    = model.predict(X_pred)[0]
        pred_amount = np.expm1(log_pred)
        rmse_log    = metrics[model_data['name']]['test_rmse'] if metrics else 0.68
        low         = np.expm1(log_pred - rmse_log)
        high        = np.expm1(log_pred + rmse_log)

        # Gauge chart
        fig_gauge = go.Figure(go.Indicator(
            mode="gauge+number",
            value=pred_amount / 1e6,
            number=dict(prefix="$", suffix="M", font=dict(size=28, color='#0f2540')),
            gauge=dict(
                axis=dict(range=[0, 5], ticksuffix="M"),
                bar=dict(color='#1e88e5'),
                steps=[
                    dict(range=[0, 1.65], color='#e8f5e9'),
                    dict(range=[1.65, 3.3], color='#fff3e0'),
                    dict(range=[3.3, 5],   color='#ffebee'),
                ],
            ),
            title=dict(text="Predicted Assistance", font=dict(size=13, color='#4a6080')),
        ))
        fig_gauge.update_layout(
            height=250, margin=dict(t=40, b=0, l=20, r=20),
            paper_bgcolor='rgba(0,0,0,0)',
        )

        g1, g2, g3 = st.columns([2, 1, 1])
        with g1:
            st.plotly_chart(fig_gauge, use_container_width=True)
            st.markdown('<div class="gauge-label">Green = Low | Orange = Moderate | Red = High relative to $5M scale</div>', unsafe_allow_html=True)
        with g2:
            st.markdown(f"""
            <div class="pred-main">
                <div class="label">Predicted Total</div>
                <div class="amount">${pred_amount:,.0f}</div>
            </div>""", unsafe_allow_html=True)
        with g3:
            st.markdown(f"""
            <div class="pred-range">
                <div class="label">Lower Estimate</div>
                <div class="amount">${low:,.0f}</div>
            </div>
            <div class="pred-range">
                <div class="label">Upper Estimate</div>
                <div class="amount">${high:,.0f}</div>
            </div>""", unsafe_allow_html=True)

        st.markdown(f"""<div class="insight-box" style="margin-top:16px;">
        <b>Interpretation:</b> For a county in <b>{pred_state}</b> with population <b>{pred_pop:,}</b>,
        median income <b>${pred_income:,}</b>, poverty rate <b>{pred_poverty:.1f}%</b>, and approximately
        <b>{pred_applicants:,}</b> disaster applicants, the model estimates
        <b>${pred_amount:,.0f}</b> in total FEMA assistance (range: ${low:,.0f} to ${high:,.0f}).
        </div>""", unsafe_allow_html=True)

    elif predict_btn and not model_data:
        st.error("Model not found. Run 'python models/train_models.py' first.")

    if not predict_btn:
        st.markdown("""<div class="insight-box">
        Fill in the county details and click <b>Run Prediction</b> to get an estimate.
        The model uses Random Forest trained on 2,888 county-year records with a test R2 of 0.895.
        </div>""", unsafe_allow_html=True)


# Footer
st.markdown("<hr class='custom-divider'>", unsafe_allow_html=True)
st.markdown(
    "<center><small style='color:#9ab0c4;'>FEMA Disaster Assistance Dashboard | "
    "Data: FEMA OpenFEMA + US Census ACS (2019-2022) | "
    "Model: Random Forest | Built with Streamlit and Plotly</small></center>",
    unsafe_allow_html=True,
)

# Tab 6: Future Scenarios
with tab6:

    st.markdown('<div class="section-header">Future Disaster Planning Scenarios</div>',
                unsafe_allow_html=True)

    st.markdown("""
    This section estimates **which counties may require the most FEMA assistance
    if future disasters occur**, based on historical patterns and socioeconomic vulnerability.
    """)

    # Component A — County Risk Map

    st.markdown("### County Risk Score Map")

    risk_df = df.copy()

    # Frequency of disasters / assistance events
    freq = risk_df.groupby(['state_clean','county_clean']).size().rename("disaster_frequency")
    risk_df = risk_df.join(freq, on=['state_clean','county_clean'])

    # Normalize frequency
    risk_df['freq_norm'] = (
        (risk_df['disaster_frequency'] - risk_df['disaster_frequency'].min()) /
        (risk_df['disaster_frequency'].max() - risk_df['disaster_frequency'].min())
    )

    # Risk score
    risk_df['risk_score'] = (
        0.6 * risk_df['vulnerability_index'].rank(pct=True) +
        0.4 * risk_df['freq_norm']
    )

    risk_state = risk_df.groupby('state_clean').agg(
        risk_score=('risk_score','mean')
    ).reset_index()

    fig_risk = px.choropleth(
        risk_state,
        locations="state_clean",
        locationmode="USA-states",
        color="risk_score",
        scope="usa",
        color_continuous_scale="Reds",
        title="Relative Disaster Assistance Risk by State"
    )

    fig_risk.update_layout(height=450)
    st.plotly_chart(fig_risk, use_container_width=True)

    st.markdown("""
    **Interpretation**

    States shown in darker red historically combine:
    - Higher socioeconomic vulnerability
    - More frequent disaster assistance events

    These areas may require **greater FEMA preparedness and resource allocation**.
    """)

    st.divider()

    # Component B — Scenario Simulator

    st.markdown("### Disaster Scenario Simulator")

    st.caption("Estimate potential FEMA assistance needs under different disaster severity scenarios.")

    s1, s2 = st.columns(2)

    with s1:
        sim_state = st.selectbox(
            "State",
            sorted(df['state_clean'].unique()),
            key="sim_state"
        )

    with s2:
        severity = st.selectbox(
            "Disaster Severity",
            ["Mild","Moderate","Severe","Catastrophic"]
        )

    severity_multiplier = {
        "Mild": 0.5,
        "Moderate": 1.0,
        "Severe": 1.8,
        "Catastrophic": 3.0
    }

    if st.button("Simulate Scenario", type="primary"):

        state_df = df[df['state_clean']==sim_state]

        avg_pop = state_df['total_population'].mean()
        avg_income = state_df['median_income'].mean()
        avg_poverty = state_df['poverty_rate'].mean()
        avg_apps = state_df['total_applicants'].mean()
        avg_housing_share = state_df['housing_share'].mean()

        model = model_data['model']
        feat_names = model_data['features']

        poverty_count = avg_poverty/100 * avg_pop
        state_mean_val = state_df['log_total_assistance'].mean()

        z_pov = (avg_poverty - df['poverty_rate'].mean()) / df['poverty_rate'].std()
        z_inc = -(avg_income - df['median_income'].mean()) / df['median_income'].std()

        vuln = (z_pov + z_inc)/2

        feat_vals = {
            'log_population': np.log1p(avg_pop),
            'log_income': np.log1p(avg_income),
            'poverty_rate': avg_poverty,
            'poverty_count': poverty_count,
            'vulnerability_index': vuln,
            'applicants_per_capita': avg_apps/avg_pop,
            'log_applicants': np.log1p(avg_apps),
            'housing_share': avg_housing_share,
            'Year': 2023,
            'state_mean_log_assistance': state_mean_val,
        }

        X = pd.DataFrame([[feat_vals[f] for f in feat_names]], columns=feat_names)

        log_pred = model.predict(X)[0]

        pred = np.expm1(log_pred)

        pred *= severity_multiplier[severity]

        st.success(f"### Estimated FEMA Assistance: ${pred:,.0f}")

        fig_gauge = go.Figure(go.Indicator(
            mode="gauge+number",
            value=pred,
            number={'prefix':"$"},
            title={'text':"Estimated Assistance"},
            gauge={
                'axis':{'range':[0, pred*1.5]},
                'bar':{'color':"#d73027"}
            }
        ))

        fig_gauge.update_layout(height=350)

        st.plotly_chart(fig_gauge, use_container_width=True)

        st.markdown("""
        **Disclaimer**

        These estimates are **scenario planning simulations**, not actual FEMA forecasts.
        Predictions are based on historical disaster assistance patterns (2019-2022)
        combined with county socioeconomic characteristics.
        """)